LineLength:
  Enabled: false

Documentation:
  Enabled: false

AsciiComments:
  Enabled: false

LiteralInInterpolation:
  Exclude:
    - 'spec/**/*'

NumericLiterals:
  Enabled: false

BlockLength:
  Enabled: false

AllCops:
  Exclude:
    - '.bundle/**/*'
    - 'berks-cookbooks/**/*'
